import { TaskDocument, TaskItem } from './types.js';

export function createDemoDocument(): TaskDocument {
  const now = new Date();
  
  // Format date helper (YYYY-MM-DD)
  const fmt = (d: Date) => d.toISOString().split('T')[0];
  const addDays = (days: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() + days);
    return fmt(d);
  };

  const items: Record<string, TaskItem> = {
    // 1. Root Project
    'item-1': {
      id: 'item-1',
      content: '🚀 Q3 Product Launch & Architecture Overhaul #milestone',
      note: 'Key company initiative for scaling our infrastructure and shipping the v2.0 features on time.',
      completed: false,
      collapsed: false,
      parentId: null,
      childIds: ['item-1-1', 'item-1-2', 'item-1-3'],
      startDate: addDays(-3),
      endDate: addDays(25),
      color: '#3b82f6',
      progress: 45,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // 1.1 Engineering
    'item-1-1': {
      id: 'item-1-1',
      content: 'Engineering & Core Platform',
      note: 'Infrastructure updates, API endpoints, and database migration.',
      completed: false,
      collapsed: false,
      parentId: 'item-1',
      childIds: ['item-1-1-1', 'item-1-1-2', 'item-1-1-3'],
      startDate: addDays(-3),
      endDate: addDays(18),
      color: '#6366f1',
      progress: 60,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-1-1': {
      id: 'item-1-1-1',
      content: 'Database schema migration to PostgreSQL 16',
      note: 'Migrate legacy tables, optimize JSONB indices, and run stress tests.',
      completed: true,
      collapsed: false,
      parentId: 'item-1-1',
      childIds: [],
      startDate: addDays(-3),
      endDate: addDays(2),
      color: '#10b981',
      progress: 100,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-1-2': {
      id: 'item-1-1-2',
      content: 'Real-time WebSocket sync engine @backend',
      note: 'Handle live collaborative edits, optimistic UI updates, and conflict resolution.',
      completed: false,
      collapsed: false,
      parentId: 'item-1-1',
      childIds: ['item-1-1-2-1', 'item-1-1-2-2'],
      startDate: addDays(2),
      endDate: addDays(11),
      color: '#8b5cf6',
      progress: 50,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-1-2-1': {
      id: 'item-1-1-2-1',
      content: 'Implement delta compression algorithm',
      note: 'Reduce network payload sizes for large task trees.',
      completed: true,
      collapsed: false,
      parentId: 'item-1-1-2',
      childIds: [],
      startDate: addDays(2),
      endDate: addDays(6),
      color: '#8b5cf6',
      progress: 100,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-1-2-2': {
      id: 'item-1-1-2-2',
      content: 'Benchmark with 10k concurrent simulated clients',
      note: 'Ensure p99 latency stays under 40ms.',
      completed: false,
      collapsed: false,
      parentId: 'item-1-1-2',
      childIds: [],
      startDate: addDays(6),
      endDate: addDays(11),
      color: '#8b5cf6',
      progress: 20,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-1-3': {
      id: 'item-1-1-3',
      content: 'Deploy staging cluster & end-to-end integration suite',
      note: 'Automated CI/CD pipeline verification.',
      completed: false,
      collapsed: false,
      parentId: 'item-1-1',
      childIds: [],
      startDate: addDays(11),
      endDate: addDays(18),
      color: '#f59e0b',
      progress: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // 1.2 Design & UX
    'item-1-2': {
      id: 'item-1-2',
      content: 'Design & User Experience (UX)',
      note: 'Design system tokens, Gantt drag-and-drop interactions, accessibility audits.',
      completed: false,
      collapsed: false,
      parentId: 'item-1',
      childIds: ['item-1-2-1', 'item-1-2-2'],
      startDate: addDays(-1),
      endDate: addDays(14),
      color: '#ec4899',
      progress: 40,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-2-1': {
      id: 'item-1-2-1',
      content: 'Figma interactive prototypes for Gantt timeline zoom',
      note: 'Fine-tune hover tooltips, resize handles, and row collapse animations.',
      completed: true,
      collapsed: false,
      parentId: 'item-1-2',
      childIds: [],
      startDate: addDays(-1),
      endDate: addDays(5),
      color: '#ec4899',
      progress: 100,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-2-2': {
      id: 'item-1-2-2',
      content: 'Keyboard accessibility & high-contrast dark mode theme',
      note: 'Ensure WCAG AA compliance and smooth keyboard-only navigation.',
      completed: false,
      collapsed: false,
      parentId: 'item-1-2',
      childIds: [],
      startDate: addDays(5),
      endDate: addDays(14),
      color: '#ec4899',
      progress: 25,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // 1.3 Marketing & Launch
    'item-1-3': {
      id: 'item-1-3',
      content: 'Go-to-Market & Launch Campaign',
      note: 'Product Hunt launch, blog post announcements, customer webinars.',
      completed: false,
      collapsed: false,
      parentId: 'item-1',
      childIds: ['item-1-3-1', 'item-1-3-2'],
      startDate: addDays(14),
      endDate: addDays(25),
      color: '#06b6d4',
      progress: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-3-1': {
      id: 'item-1-3-1',
      content: 'Draft technical blog post and interactive demo video',
      note: 'Record GIF walkthroughs showcasing the Outliner and Gantt zoom view.',
      completed: false,
      collapsed: false,
      parentId: 'item-1-3',
      childIds: [],
      startDate: addDays(14),
      endDate: addDays(20),
      color: '#06b6d4',
      progress: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-1-3-2': {
      id: 'item-1-3-2',
      content: 'Public Product Hunt and Hacker News release',
      note: 'Target date for official public launch.',
      completed: false,
      collapsed: false,
      parentId: 'item-1-3',
      childIds: [],
      startDate: addDays(20),
      endDate: addDays(25),
      color: '#06b6d4',
      progress: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // 2. Personal Quick Tasks
    'item-2': {
      id: 'item-2',
      content: 'Personal Daily Focus & Ideas',
      note: 'Infinitely nested tasks with full outliner power. Press Enter for new items, Tab to indent.',
      completed: false,
      collapsed: false,
      parentId: null,
      childIds: ['item-2-1', 'item-2-2', 'item-2-3'],
      startDate: addDays(0),
      endDate: addDays(7),
      color: '#14b8a6',
      progress: 33,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-2-1': {
      id: 'item-2-1',
      content: 'Morning review and calendar check #daily',
      completed: true,
      collapsed: false,
      parentId: 'item-2',
      childIds: [],
      startDate: addDays(0),
      endDate: addDays(1),
      color: '#14b8a6',
      progress: 100,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-2-2': {
      id: 'item-2-2',
      content: 'Deep work block: Architecture and performance pass',
      note: 'Set timer for 90 minutes. Do not check social media or email.',
      completed: false,
      collapsed: false,
      parentId: 'item-2',
      childIds: [],
      startDate: addDays(1),
      endDate: addDays(4),
      color: '#14b8a6',
      progress: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    'item-2-3': {
      id: 'item-2-3',
      content: 'Weekly retrospective & cleanup',
      completed: false,
      collapsed: false,
      parentId: 'item-2',
      childIds: [],
      startDate: addDays(5),
      endDate: addDays(7),
      color: '#14b8a6',
      progress: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  };

  return {
    id: 'doc-welcome',
    title: 'Getting Started with DiviTask',
    rootItemIds: ['item-1', 'item-2'],
    items,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
